### ISSUE TITLE
[Bug]: Fails to run scripts for failing to initialize `NativeMemory` in game version v1.0.3258.0

### ISSUE THREAD

**Issue by kagikn** [scripthookvdotnet/scripthookvdotnet#1451]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

between d585fa3 and fdd933b

### Game Version

v1.0.3258.0

### Bug Description

In v1.0.3258.0, SHVDN fails to initialize for some memory patterns not found, making it impossible to run almost any scripts.

Here's a known lines where `NativeMemory` throws a `System.NullReferenceException` for the address being not found and left being null:
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/fdd933be82f4d50aa4756582d0c26ab2fecf61e1/source/core/NativeMemory.cs#L263-L264

### Steps To Reproduce

1. Launch the game
2. See if `ScriptHookVDotNet.log` says a `System.NullReferenceException` is thrown from `SHVDN.NativeMemory`

### The Current Behavior

`NativeMemory` throws an exception before finishing initalization

### The Expected Behavior

`NativeMemory` finishes initalization

**Comment by ShadowSoftware0** [comment]
How To Fix It ?

**Comment by kagikn** [comment]
Fixed the issue! In the nightly version `nightly-89` and later, you won't have it! Check out [nightly releases](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases) for the fix! The same thing *will* apply to v3.7.0 after getting released!

@ShadowSoftware0

**Comment by EminGT** [comment]
This might have not been fully fixed in nightly-89 or above. It still crashes for me regardless of the build and it doesn't crash if I just delete the svdn files

**Comment by EminGT** [comment]
I also just tried with no other mods/scripts and still crashes (nightly-93). But for some reason The nightly-90 build specifically seems to not crash sometimes but I couldn't figure out why that is. It's just weird. I can do more testing for you if you can tell me to try some things

**Comment by EminGT** [comment]
Okay should I make a new issue report for that or are you already aware of the problem?

**Comment by kagikn** [comment]
@EminGT Try [nighly.94](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.94) (or later) first as I think I fixed more possible causes of the game crash for some people. If you still suffer some game crash even with that version, I think you might as well make a new issue. Sorry, I can't reproduce such game crashes since I only tested with a kinda shitty PC (a Haswell one). Report from someone other than me would help me.

**Comment by ivan33944** [comment]
In second mission in the game cutscene is broken.Simon dont moving.

**Comment by julius499** [comment]
scripts no longer work, none

**Comment by Pixerr** [comment]
i tried using every nightly from 89 to 96 and none worked. i even tried it without nightly. any ideas?

**Comment by KernelPryanic** [comment]
Well, just wanted to play GTA with mods today, tried to install my old mods and found out they don't work anymore, migrated from NativeUI to LemonUI, but apparently it seems that I'm just in time to some GTA update that broke SHVDN 😅

**Comment by KernelPryanic** [comment]
Rebuilt the mod with the latest nightly build. Can confirm that [v3.6.0-nightly.96](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.96) works for me.

**Comment by ProPrinses** [comment]
> Rebuilt the mod with the latest nightly build. Can confirm that [v3.6.0-nightly.96](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.96) works for me.

How did you rebuild the mod? by adding .2 to the file?

**Comment by KernelPryanic** [comment]
> > Rebuilt the mod with the latest nightly build. Can confirm that [v3.6.0-nightly.96](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.96) works for me.
> 
> How did you rebuild the mod? by adding .2 to the file?

I just rebuilt the project using `dotnet build`. You can find both mods in my profile if you want.
